#pragma once




// works

enum Buttons
{
	BuTTON_TRIANGLE = 0xB4,
	BuTTON_O = 0xC0,
	BuTTON_X = 0xCD,
	BuTTON_SQUARE = 0xBF,
	BuTTON_L1 = 0xC1,
	BuTTON_L2 = 0xC3,
	BuTTON_L3 = 0xC5,
	BuTTON_R1 = 0xC2,
	BuTTON_R2 = 0xC4,
	BuTTON_R3 = 0xC6,
	DpAD_UP = 0xC7,
	DpAD_RIGHT = 0xCA,
	DpAD_LEFT = 0xC9,
	DpAD_DOWN = 0xA1,
	BuTTON_SELECT = 0xCB,
	BuTTON_START = 0x0F
};
/* GTA 5 maybe 1.27
enum Buttons
{
	BuTTON_X = 0xC1,
	BuTTON_O = 0xC3,
	BuTTON_SQUARE = 0xC2,
	BuTTON_TRIANGLE = 0xC0,
	BuTTON_SELECT = 0xBF,
	BuTTON_L1 = 0xC4,
	BuTTON_L2 = 0xC6,
	BuTTON_L3 = 0xC8,
	BuTTON_R1 = 0xC5,
	BuTTON_R2 = 0xC7,
	BuTTON_R3 = 0xC9,
	DpAD_UP = 0xCA,
	DpAD_DOWN = 0xCB,
	DpAD_LEFT = 0xCC,
	DpAD_RIGHT = 0xCD
};
*/

enum ScaleformButtons
{
	ARROW_UP,
	ARROW_DOWN,
	ARROW_LEFT,
	ARROW_RIGHT,
	BUTTON_DPAD_UP,
	BUTTON_DPAD_DOWN,
	BUTTON_DPAD_RIGHT,
	BUTTON_DPAD_LEFT,
	BUTTON_DPAD_BLANK,
	BUTTON_DPAD_ALL,
	BUTTON_DPAD_UP_DOWN,
	BUTTON_DPAD_LEFT_RIGHT,
	BUTTON_LSTICK_UP,
	BUTTON_LSTICK_DOWN,
	BUTTON_LSTICK_LEFT,
	BUTTON_LSTICK_RIGHT,
	BUTTON_LSTICK,
	BUTTON_LSTICK_ALL,
	BUTTON_LSTICK_UP_DOWN,
	BUTTON_LSTICK_LEFT_RIGHT,
	BUTTON_LSTICK_ROTATE,
	BUTTON_RSTICK_UP,
	BUTTON_RSTICK_DOWN,
	BUTTON_RSTICK_LEFT,
	BUTTON_RSTICK_RIGHT,
	BUTTON_RSTICK,
	BUTTON_RSTICK_ALL,
	BUTTON_RSTICK_UP_DOWN,
	BUTTON_RSTICK_LEFT_RIGHT,
	BUTTON_RSTICK_ROTATE,
	BUTTON_A,
	BUTTON_B,
	BUTTON_X,
	BUTTON_Y,
	BUTTON_LB,
	BUTTON_LT,
	BUTTON_RB,
	BUTTON_RT,
	BUTTON_START,
	BUTTON_BACK,
	RED_BOX,
	RED_BOX_1,
	RED_BOX_2,
	RED_BOX_3,
	LOADING_HALF_CIRCLE_LEFT,
	ARROW_UP_DOWN,
	ARROW_LEFT_RIGHT,
	ARROW_ALL,
	LOADING_HALF_CIRCLE_LEFT_2,
	SAVE_HALF_CIRCLE_LEFT,
	LOADING_HALF_CIRCLE_RIGHT,
};

enum Submenus
{
	Closed,
	Main_Menu,
	Players_List,
	Network_menu,
	Player_Options,
	Self_Options,
	Settings,
	Settings_Banners,
	Settings_Body,
	Settings_Scroller,
	Settings_Indicators,
	Credits,
	Recovery,
	Rank_menu,
	PresetRanks_Menu,
	Vechicle,
	Weapon_Menu,
	TeleportMenu,
	MiscMenu,
	Friends_List,
	Tunable_menu,
	VehicleSpawnerMenu,
	VehicleSpawnerSettingsMenu,
	SuperCars,
	SportsCars,
	TeleportShopMenu,
	CommonTeleport,
	NicePlayerOtions,
	MalicousPlayersOptions,
	AnimationPlayerOptions,
	DevOptions,
	Animation_Options,
	Model_menu,
	Invite_menu,
	UtilityCars,
	Vanslist,
	ServiceVehicles,
	Sedans,
	EmergencyVehicles,
	Boats,
	Offroad,
	Motocycles,
	Planes_menu,
	MuscleCars,
	SUV_menu,
	Helicopters_Menu,
	MilitaryVeh_menu,
	CommercialVeh_menu,
	CompactsVeh_menu,
	CyclesVeh_menu,
	Industrialveh_menu,
	CoupesVeh_menu,
	TrainsVeh_menu,
	Weather_menu,
	Time_menu,
	Spoof_menu,
	Patch_natives_menu,
	IPLLoadMenu,
	RadioMenu,
	CustomHud,
	CustomHudChooserMenu,
	SettingsSizeMenu,
	DrawingMenu,
	DrawBoxMenu,
	DrawTextMenu,
	CustomNameMenu,
	ProtectionMenu,
	TunablesMenu
};

enum KeyboardInputs
{
	AddInt,
	VehicleNumberPlate,
	NameChanger,
	InviteByPSN,
	DBGText,
	TextVehSpawner,
	UsernameModMenu,
	UGCload

};

enum evProtections {
	KickProtection,
	FakeLeaveProtection,
	AnimationTeleport
};